version: '3'

services: 
  demo-service:
    image: demo-service
    container_name: demo-service
    build: 
      context: .
      args:
        PROJECT_DIR: $PWD
    # env_file: .env
    environment: 
      - VAR=$VAR
    ports: 
      - "3000:3000"
    volumes: 
      - .:$PWD
    command: ["npm", "run", "dev"]